@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniquePersonList
AddressBook *-right-> "1" UniqueTagList
AddressBook *-right-> "1" UniqueModTutGroupList
UniqueTagList -[hidden]down- UniquePersonList
UniqueTagList -[hidden]down- UniquePersonList

UniqueTagList -right-> "*" Tag
UniquePersonList -right-> Person
UniqueModTutGroupList -right-> "*" ModTutGroup

Person -up-> "*" Tag

Person *--> Name
Person *--> Telegram
Person *--> Email
Person *--> "1..*" ModTutGroup

ModTutGroup *--> "1" Module
ModTutGroup *--> "1" Tutorial
@enduml
