@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes find command with keyword(s);
:ConnectS parses keyword(s);
'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.
switch()
case( [name keyword])
    :Create a name predicate;
case ( [email keyword])
    :Create an email predicate;
case( [telegram handle keyword])
    :Create a telegram handle predicate;

endswitch
:Filter list of tutees using predicate;
:Show filtered list to user;
stop
@enduml
